apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-10-03T15:27:35Z"
  generation: 1
  name: quota-positive
  namespace: group04
  resourceVersion: "4504"
  uid: 61794b6d-13a9-44f8-9c97-6755934590de
spec:
  containers:
  - image: python:3.11-slim
    imagePullPolicy: IfNotPresent
    name: quota-positive
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2c24k
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: desktop-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-2c24k
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  allocatedResources:
    cpu: 100m
    memory: 128Mi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-10-03T15:27:35Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-10-03T15:27:35Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-10-03T15:27:47Z"
    message: 'containers with unready status: [quota-positive]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-10-03T15:27:47Z"
    message: 'containers with unready status: [quota-positive]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-10-03T15:27:35Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 100m
      memory: 128Mi
    containerID: containerd://cee066d16aa5b649fbe7f37ca93c8385251bf9a8a8a6021bd3d18c75b1868861
    image: docker.io/library/python:3.11-slim
    imageID: docker.io/library/python@sha256:bab1b7ef4b450c81002278d035eff85ebe394ae94df904f7a3ba14f7e16e487b
    lastState:
      terminated:
        containerID: containerd://1801d9f5a293520298f163ef617ae5bc57baa157596daf8131048d8e33594f32
        exitCode: 0
        finishedAt: "2026-10-03T15:27:36Z"
        reason: Completed
        startedAt: "2026-10-03T15:27:36Z"
    name: quota-positive
    ready: false
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    restartCount: 2
    started: false
    state:
      terminated:
        containerID: containerd://cee066d16aa5b649fbe7f37ca93c8385251bf9a8a8a6021bd3d18c75b1868861
        exitCode: 0
        finishedAt: "2026-10-03T15:27:47Z"
        reason: Completed
        startedAt: "2026-10-03T15:27:47Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2c24k
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.18.0.2
  hostIPs:
  - ip: 172.18.0.2
  observedGeneration: 1
  phase: Running
  podIP: 10.244.0.6
  podIPs:
  - ip: 10.244.0.6
  qosClass: Burstable
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 79m
      memory: 128Mi
  startTime: "2026-10-03T15:27:35Z"
