apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"observer","namespace":"group04"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"observer"},"subjects":[{"kind":"ServiceAccount","name":"observer","namespace":"group04"}]}
  creationTimestamp: "2026-10-03T15:26:56Z"
  name: observer
  namespace: group04
  resourceVersion: "4405"
  uid: 70c7d47f-d657-447c-a515-a9d420af7f39
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: observer
subjects:
- kind: ServiceAccount
  name: observer
  namespace: group04
