apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"observer","namespace":"group04"},"rules":[{"apiGroups":[""],"resources":["pods","pods/log","events"],"verbs":["get","list","watch"]}]}
  creationTimestamp: "2026-10-03T15:26:56Z"
  name: observer
  namespace: group04
  resourceVersion: "4404"
  uid: c9b17797-b7b7-4c5b-a932-de72d9332541
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - events
  verbs:
  - get
  - list
  - watch
