apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","automountServiceAccountToken":false,"kind":"ServiceAccount","metadata":{"annotations":{},"name":"observer","namespace":"group04"}}
  creationTimestamp: "2026-10-03T15:26:56Z"
  name: observer
  namespace: group04
  resourceVersion: "4403"
  uid: 053f2fbe-5197-4a13-8c00-a373e77f7544
