apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"objects","namespace":"group04"},"spec":{"ports":[{"name":"s3","port":8333,"targetPort":"s3"}],"selector":{"app":"objects"},"type":"ClusterIP"}}
  creationTimestamp: "2026-10-03T15:43:50Z"
  name: objects
  namespace: group04
  resourceVersion: "5962"
  uid: 7f957ffc-f6a3-4d9a-bcc6-6a11b5d1a6fe
spec:
  clusterIP: 10.96.89.252
  clusterIPs:
  - 10.96.89.252
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: s3
    port: 8333
    protocol: TCP
    targetPort: s3
  selector:
    app: objects
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
